export const FRASES = [
  "Mas olha Cuba!",
  "Na Venezuela é assim também",
  "Vai pra Cuba então!",
  "O PT acabou com o Brasil",
  "Isso é coisa de comunista",
  "Querem transformar o Brasil na Venezuela",
  "Bolsa família é esmola",
  "Socialismo nunca deu certo",
  "Comunismo matou milhões",
  "A esquerda quer doutrinar nas escolas",
  "O Foro de SP planejou tudo",
  "Olha a Argentina!",
  "O comunismo acabou com tudo na URSS",
  "Querem acabar com a propriedade privada",
  "Esses vagabundos da universidade",
  "Quem trabalha vence",
  "Escola tem que ensinar, não lacrar",
  "Meritocracia acima de tudo",
  "Isso é coisa de maconheiro da USP",
  "Petista adora viver com o dinheiro dos outros",
  "O empresário é quem gera empregos",
  "Quem quer, corre atrás",
  "Quer tudo de graça do governo",
  "Capitalismo é liberdade",
  "Com esse pensamento, ninguém vai querer trabalhar",
  "Comunista de iPhone",
  "Quer dividir o que é dos outros",
  "Se não gosta do sistema, vai embora",
  "O estado só atrapalha",
  "Imposto é roubo",
  "Lula livre foi um absurdo",
  "A mamata acabou",
  "Tinha que privatizar tudo",
  "Esses vagabundos do MST",
  "Ditadura militar foi necessária",
  "Na época dos militares era melhor",
  "Bolsonaro foi o melhor presidente",
  "Não tem corrupção no governo atual",
  "A mídia é comunista",
  "A Globo manipula tudo",
  "Não existe fome no Brasil",
  "Estão inventando racismo",
  "Tudo agora é homofobia",
  "Não pode mais nem brincar",
  "Esses professores doutrinadores",
  "Ah, mas e o mensalão?",
  "Nunca vi pobre empreendedor reclamar",
  "Comunismo só gera miséria",
  "A esquerda quer destruir a família",
  "O problema é o comunismo cultural"
]